name: Build Plugin
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  PLUGIN_NAME: Lidarr.Plugin.Tidal
  DOTNET_VERSION: 8.0.404

jobs:
  build:
    strategy:
      matrix:
        framework: [ net6.0 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Create global.json
        run: |
          echo '{"sdk":{"version": "${{ env.DOTNET_VERSION }}"}}' > ./global.json
      - name: Generate metadata
        id: gen_meta
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" | tr '/' '-'  >> $GITHUB_OUTPUT
      - name: Build
        run: dotnet publish src/*.sln -c Release -f ${{ matrix.framework }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.framework }}
          path: ./${{ env.PLUGIN_NAME }}.${{ matrix.framework }}.zip